Tdl 20245 fix vistor history bookmarking
singer-io/tap-pendo pull request #108
Opened 2022-08-12 17:07 UTC by RushiT0122

# Description of change
    - Implemented new bookmark strategy for child streams
    - Updated record_limit value exception handling
    - Updated tap-tester start dates to reduce execution time
    - Added new unittests to test record limit and visitor history start date 
    - Updated no start date unittests

# Manual QA steps
 - Verified the new bookmark strategy working as expected 
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

2022-08-16 07:24 UTC, dbshah1212 commented on tap_pendo/streams.py
> +        # last processed is none when all events/history of all parents is processed
```suggestion
        # Last processed is none when all events/history of all parents is processed
```

2022-08-16 07:25 UTC, dbshah1212 commented on tap_pendo/__init__.py
> +        # parent stream will sync sub stream
```suggestion
        # Parent stream will sync sub stream
```

2022-08-16 07:59 UTC, shantanu73 commented on tap_pendo/streams.py
> +# This dict should be ordered so that child stream(s) are occuring just above parent stream.
```suggestion
# This dict is ordered so that child stream(s) are occurring just above parent stream.
```

2022-08-16 09:08 UTC, dbshah1212 commented on tap_pendo/streams.py
> +    return error.response is not None and 400 <= error.response.status_code < 500
Are there any chances where the response came without status_code? Because that isn't handled.

2022-08-16 09:14 UTC, dbshah1212 commented on tap_pendo/streams.py
>          # If last sync was interrupted, get last processed parent record
Seems like we are fetching bookmarks, not records.

2022-09-06 13:49 UTC, bryantgray approved these changes

2022-09-06 17:28 UTC, kspeer825 requested changes

2022-09-06 17:28 UTC, kspeer825 commented on tests/tap_tester/test_all_fields.py
> +                #     expected_all_keys = expected_all_keys - {'audience'}
Can this just be removed?

2022-09-06 17:28 UTC, kspeer825 commented on tests/tap_tester/test_all_fields.py
> +        }
It's a bit confusing to remove this from the expectations in base.py then add back here. I think a more consistent pattern with what we have used in the past is to make the expected_metadata in base.py a constant source of truth for defining the expectations of a stream. Then if a stream cannot be included in a specific test, jut removing it from the streams under test.

2022-09-06 17:28 UTC, kspeer825 commented on tests/tap_tester/test_visitor_history_bookmark.py
> +                    )
This section does not apply to either stream under test. This seems to be the exact same bookmarks test with just fewer streams under test. It's fine if you want a separate test file for these streams, but I think it should inherit the test class from the existing bookmarks test so the test doesn't have to be maintained in 2 places in the suite.

2022-09-07 18:38 UTC, kspeer825 approved these changes

2022-12-19 13:32 UTC, shantanu73 approved these changes

2022-12-19 14:29 UTC, merged