Add filter parameter and record limit to resolve OOM
singer-io/tap-pendo pull request #116
Opened 2023-03-21 15:22 UTC by RushiT0122

# Description of change
Connection failures observed with OOM issues or request timeouts for non-event based streams. Primary reason for that is we are trying to pull all data at once which sometimes causes OOM or request timeouts.

We had fixed similar issue for event based streams in the past so extended and generalised similar fix to all applicable streams.

- Added filter, sorting and limit parameters to applicable incremental streams 
- Moved common methods to parent classes
- Changed inheritance for `events` and `poll_events` streams
- Write unittests

# Manual QA steps
 - Ran integration tests on local dev env and verified the fix
 - Ran unittests
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

2023-03-23 18:25 UTC, zachharris1 requested changes

2023-03-27 15:41 UTC, zachharris1 approved these changes

2023-03-29 08:43 UTC, sgandhi1311 commented
Can we update the README.md for the `record_limit` parameter?

2023-03-30 04:49 UTC, sgandhi1311 approved these changes

2023-03-30 09:58 UTC, merged